# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"
      - "9229:9229"
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
