exports.seed = async (knex) => knex('investment_funds').insert([{
  id: 0,
  creatorId: 1,
  currencyCode: 'BTC',
  balance: 12,
  name: 'Super Investment Fund',
  shortDescription: 'This is a super investment fund guaranteed to triple your money in 1 month',
}, {
  id: 1,
  creatorId: 1,
  currencyCode: 'BTC',
  balance: 0,
  name: 'Ok Investment Fund',
  shortDescription: 'Maybe a bit of money, maybe not. Who knows.',
}, {
  id: 2,
  creatorId: 1,
  currencyCode: 'BTC',
  balance: 0,
  name: 'Lame Investment Fund',
  shortDescription: 'Investing in this one means you will lose your money',
}, {
  id: 3,
  creatorId: 1,
  currencyCode: 'BTC',
  balance: 0,
  name: 'Rainy day fund',
  shortDescription: 'We make money on rainy days for some reason. Join now.',
}, {
  id: 4,
  creatorId: 1,
  currencyCode: 'BTC',
  balance: 0,
  name: 'Rapper Fund',
  shortDescription: 'Fund investing in local soundcloud rappers',
}]);