const { daysAgo } = require('../../utils');
exports.seed = async knex => knex('investment_fund_balance_updates').insert([{
  investmentFundId: 1,
  previousBalance: 10,
  updatedBalance: 11,
  previousSharePrice: 1,
  updatedSharePrice: 1.1,
  createdAt: daysAgo(45),
  updatedAt: daysAgo(45),
},{
  investmentFundId: 1,
  previousBalance: 11,
  updatedBalance: 13,
  previousSharePrice: 1.1,
  updatedSharePrice: 1.3,
  createdAt: daysAgo(40),
  updatedAt: daysAgo(40),
},{
  investmentFundId: 1,
  previousBalance: 13,
  updatedBalance: 11.4,
  previousSharePrice: 1.3,
  updatedSharePrice: 1.14,
  createdAt: daysAgo(27),
  updatedAt: daysAgo(27),
},{
  investmentFundId: 1,
  previousBalance: 11.4,
  updatedBalance: 15.2,
  previousSharePrice: 1.14,
  updatedSharePrice: 1.52,
  createdAt: daysAgo(17),
  updatedAt: daysAgo(17),
},{
  investmentFundId: 1,
  previousBalance: 15.2,
  updatedBalance: 17.2,
  previousSharePrice: 1.52,
  updatedSharePrice: 1.72,
  createdAt: daysAgo(17),
  updatedAt: daysAgo(17),
}, {
  investmentFundId: 1,
  previousBalance: 17.2,
  updatedBalance: 21.1,
  previousSharePrice: 1.71,
  updatedSharePrice: 2.11,
  createdAt: daysAgo(2),
  updatedAt: daysAgo(2),
}]);
